feat(assets): add purge option

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -28,6 +28,7 @@ wait_until_ready=$(jq -r '.params.wait_until_ready // 0' < $payload)
 debug=$(jq -r '.params.debug // "false"' < $payload)
 replace=$(jq -r '.params.replace // "false"' < $payload)
 delete=$(jq -r '.params.delete // "false"' < $payload)
+purge=$(jq -r '.params.purge // "false"' < $payload)
 devel=$(jq -r '.params.devel // "false"' < $payload)
 override_values=$(jq -r ".params.override_values[]? | if .key and .value and (.hide // false) == false then (.key + \"=\" + .value) else empty end | @base64"  < $payload)
 override_values_file=$(jq -r ".params.override_values[]? | if .key and .path and (.hide // false) == false then (.key + \"=\" + .path) else empty end" < $payload)
@@ -210,6 +211,26 @@ helm_delete() {
   echo "Running command $helm_echo"
   eval $helm_cmd
 }
+ 
+helm_purge() {
+  if [ -z "$release" ]; then
+    echo "invalid payload (missing release if delete=true)"
+    exit 1
+  fi
+  echo "Deleting with purge the release $release..."
+  helm_cmd="helm delete --purge"
+  helm_echo="helm delete --purge"
+  if [ "$debug" = true ]; then
+    helm_cmd="$helm_cmd --dry-run --debug"
+    helm_echo="$helm_echo --dry-run --debug"
+  fi
+  logfile="/tmp/log"
+  mkdir -p /tmp
+  helm_cmd="$helm_cmd $release | tee $logfile"
+  helm_echo="$helm_echo $release | tee $logfile"
+  echo "Running command $helm_echo"
+  eval $helm_cmd
+}
 
 wait_ready() {
   if [ -n "$wait_until_ready" ] && [ "$wait_until_ready" -gt "0" ]; then
@@ -220,7 +241,11 @@ wait_ready() {
 
 
 if [ "$delete" = true ]; then
-  helm_delete
+  if [ "$purge" = true ]; then
+    helm_purge
+  else
+    helm_delete
+  fi
   result="$(jq -n "{version:{release:\"$release\", deleted: \"true\"}, metadata: [{name: \"release\", value: \"$release\"}]}")"
   echo "$result" | jq -s add  >&3
 else
